from . import flags

BALL = flags.TRANSFORM | flags.BALLISTIC | flags.RECT_COLLIDER
PADDLE = flags.TRANSFORM | flags.RECT_COLLIDER | flags.PADDLE_CONTROL
PLAYER_PADDLE = flags.PADDLE_CONTROL | flags.PLAYER_CONTROLLER
NPC_PADDLE = flags.PADDLE_CONTROL | flags.AI_CONTROLLER
RECT_COLLIDERS = flags.TRANSFORM | flags.RECT_COLLIDER | flags.COLLIDER
TEMPORIAL = flags.TEMPORIAL
HUD = flags.SCORE_HUD

# Renderables
CIRCLE = flags.TRANSFORM | flags.CIRCLE_SPRITE
RECT = flags.TRANSFORM | flags.RECT_SPRITE
TEXT = flags.TRANSFORM | flags.TEXT_SPRITE

